
all:
	gcc denglu.c -o denglu -lsqlite3
	gcc zhuce.c -o zhuce -lsqlite3
	gcc jizhudizhi.c -o jizhudizhi -lsqlite3
	gcc tianjiahaoyou.c -o tianjiahaoyou -lsqlite3
	gcc liaotian.c -o liaotian -lsqlite3
	gcc start.c -o start 

clean:
	rm denglu zhuce jizhudizhi tianjiahaoyou liaotian start
